### ISSUE TITLE
Not Adding File to njsproj

### ISSUE THREAD

**Issue by CindyConway** [berkansivri/VsCode-njsproj#2]
Hi!

Thank you for creating this component. Our team finds it very helpful.

I am on vsCode 1.45.1 and when I install version 5.1 of the extension it doesn't work. The njsproj file does not get updated. When I execute 'Enable njsprog' from the command pallet, it says the extension cannot be found. Let me know if I can give you other info to help. For now I am using 5.0.

**Comment by berkansivri** [comment]
@CindyConway I just published a new version with some fixes. Check out, it must have solve your problem. If you encounter any bug, please let me know anyway.
